name: Run Telenor Bot
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          BOT_TOKEN: "8647027040:AAH6a8mpTBylHbbB6XBbaLvZz72PpETMwwE"
